using SQLite;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace Mapsui48.Client
{
    public class BoundingBox
    {
        public double MinLat { get; set; }
        public double MinLon { get; set; }
        public double MaxLat { get; set; }
        public double MaxLon { get; set; }
    }

    public class TileDownloaderEngine
    {
        [Table("tiles")]
        public class TilesRow
        {
            [Column("zoom_level")]
            public int ZoomLevel { get; set; }
            [Column("tile_column")]
            public int TileColumn { get; set; }
            [Column("tile_row")]
            public int TileRow { get; set; }
            [Column("tile_data")]
            public byte[] TileData { get; set; }
        }

        [Table("metadata")]
        public class MetadataRow
        {
            [Column("name")]
            public string Name { get; set; }
            [Column("value")]
            public string Value { get; set; }
        }

        public static int LonToX(double lon, int z) 
        {
            return (int)Math.Floor((lon + 180.0) / 360.0 * (1 << z));
        }

        public static int LatToY(double lat, int z) 
        {
            var latRad = lat * Math.PI / 180.0;
            return (int)Math.Floor((1.0 - Math.Log(Math.Tan(latRad) + 1.0 / Math.Cos(latRad)) / Math.PI) / 2.0 * (1 << z));
        }

        public static int CalculateTotalTiles(BoundingBox bbox, int minZoom, int maxZoom)
        {
            int total = 0;
            for (int z = minZoom; z <= maxZoom; z++)
            {
                var minX = LonToX(bbox.MinLon, z);
                var maxX = LonToX(bbox.MaxLon, z);
                var minY = LatToY(bbox.MaxLat, z); // MaxLat has smaller Y
                var maxY = LatToY(bbox.MinLat, z); // MinLat has larger Y

                total += (Math.Max(0, maxX - minX) + 1) * (Math.Max(0, maxY - minY) + 1);
            }
            return total;
        }

        public static async Task DownloadRegionAsync(
            string outputPath, 
            BoundingBox bbox, 
            int minZoom, 
            int maxZoom, 
            string urlTemplate, 
            IProgress<int> progress, 
            CancellationToken token)
        {
            var isVector = urlTemplate.Contains(".pbf") || urlTemplate.Contains(".mvt") || urlTemplate.Contains("VectorTileServer");
            var format = isVector ? "pbf" : "png";

            SQLitePCL.Batteries_V2.Init();
            using var db = new SQLiteConnection(outputPath);
            db.CreateTable<MetadataRow>();
            db.CreateTable<TilesRow>();

            // SQLite MBTiles standard schema index
            db.Execute("CREATE UNIQUE INDEX IF NOT EXISTS tile_index ON tiles (zoom_level, tile_column, tile_row);");

            // Write metadata
            db.Insert(new MetadataRow { Name = "name", Value = "DownloadedMap" });
            db.Insert(new MetadataRow { Name = "type", Value = "baselayer" });
            db.Insert(new MetadataRow { Name = "version", Value = "1" });
            db.Insert(new MetadataRow { Name = "description", Value = "Map generated by Mapsui48 Downloader" });
            db.Insert(new MetadataRow { Name = "format", Value = format });
            db.Insert(new MetadataRow { Name = "bounds", Value = $"{bbox.MinLon},{bbox.MinLat},{bbox.MaxLon},{bbox.MaxLat}" });

            using var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.UserAgent.ParseAdd("Mapsui48Downloader/1.0");

            int completed = 0;

            for (int z = minZoom; z <= maxZoom; z++)
            {
                var minX = LonToX(bbox.MinLon, z);
                var maxX = LonToX(bbox.MaxLon, z);
                var minY = LatToY(bbox.MaxLat, z);
                var maxY = LatToY(bbox.MinLat, z);

                for (int x = minX; x <= maxX; x++)
                {
                    for (int y = minY; y <= maxY; y++)
                    {
                        token.ThrowIfCancellationRequested();

                        string url = urlTemplate
                            .Replace("{z}", z.ToString())
                            .Replace("{x}", x.ToString())
                            .Replace("{y}", y.ToString());

                        try
                        {
                            var data = await httpClient.GetByteArrayAsync(url);

                            // TMS stores Y inverted
                            int tmsY = (1 << z) - 1 - y;

                            // Insert manually to ensure correct REPLACE behavior if duplicates exist,
                            // since InsertOrReplace requires PrimaryKey which MBTiles schema doesn't strictly enforce natively (it uses unique index)
                            db.Execute("INSERT OR REPLACE INTO tiles (zoom_level, tile_column, tile_row, tile_data) VALUES (?, ?, ?, ?)", 
                                z, x, tmsY, data);
                        }
                        catch (Exception)
                        {
                            // Skip failures or log them
                        }

                        completed++;
                        progress?.Report(completed);
                    }
                }
            }
        }
    }
}
